# Generated by Django 4.2.10 on 2024-02-23 12:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('items', models.JSONField(default=dict)),
                ('deals', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('Ready', 'Ready'), ('Enqueue', 'Enqueue'), ('Completed', 'Completed'), ('Cancel', 'Cancel')], default='Enqueue', max_length=20)),
                ('order_type', models.CharField(choices=[(None, 'None'), ('Lunch', 'Lunch'), ('Dinner', 'Dinner')], default=None, max_length=25)),
                ('total_price', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.customersmodel')),
            ],
            options={
                'verbose_name_plural': 'Orders',
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_id', models.PositiveBigIntegerField(editable=False, unique=True)),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='invoice', to='orders.orders')),
            ],
        ),
    ]
