# Generated by Django 4.2.10 on 2024-03-04 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='order_type',
            field=models.CharField(choices=[('Lunch', 'Lunch'), ('Dinner', 'Dinner')], max_length=25),
        ),
        migrations.AlterField(
            model_name='orders',
            name='total_price',
            field=models.PositiveIntegerField(),
        ),
    ]
