# Generated by Django 4.2.10 on 2024-03-05 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_alter_orders_deals_alter_orders_items'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='deals',
            field=models.JSONField(default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='orders',
            name='items',
            field=models.JSONField(default=dict, null=True),
        ),
    ]
