# Generated by Django 4.2.10 on 2024-03-05 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_alter_orders_deals_alter_orders_items'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orders',
            old_name='order_type',
            new_name='orderType',
        ),
        migrations.RenameField(
            model_name='orders',
            old_name='total_price',
            new_name='total',
        ),
    ]
