# Generated by Django 4.2.10 on 2024-03-06 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoicesent',
            name='total_price',
        ),
    ]
