# Generated by Django 4.2.10 on 2024-03-06 09:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_orders_order_type_alter_orders_total_price'),
        ('sales', '0002_remove_invoicesent_total_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainbalance',
            name='order_id',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='orders.orders'),
        ),
    ]
