# Generated by Django 4.2.10 on 2024-03-06 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_mainbalance_order_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainbalance',
            name='totalbalance',
            field=models.PositiveIntegerField(default=True),
        ),
    ]
