# Generated by Django 4.2.10 on 2024-03-06 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0004_mainbalance_totalbalance'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MainBalance',
        ),
    ]
