# Generated by Django 4.2.10 on 2024-03-06 18:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
        ('sales', '0006_remove_paymenthistory_customer_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymenthistory',
            name='customer_name',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to='customers.customersmodel'),
        ),
    ]
