# Generated by Django 4.2.10 on 2024-03-06 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0010_rename_customer_name_paymenthistory_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paymenthistory',
            old_name='name',
            new_name='customer',
        ),
    ]
