# Generated by Django 4.2.10 on 2024-03-06 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0011_rename_name_paymenthistory_customer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paymenthistory',
            old_name='customer',
            new_name='customer_name',
        ),
    ]
