# Generated by Django 4.2.10 on 2024-03-10 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0012_rename_customer_paymenthistory_customer_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymenthistory',
            name='customer_name',
        ),
        migrations.DeleteModel(
            name='InvoiceSent',
        ),
        migrations.DeleteModel(
            name='PaymentHistory',
        ),
    ]
